# Generated by Django 5.1.7 on 2025-03-30 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_destination_branch_shipment_origin_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yuk', 'verbose_name_plural': 'Yuklar'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, help_text='Bu yukni kuryerga biriktirish uchun', limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender',
            field=models.ForeignKey(help_text="Trek raqam, UUID ko'rinishida", on_delete=django.db.models.deletion.CASCADE, related_name='sent_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
