# Generated by Django 5.1.7 on 2025-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_options_shipment_assigned_courier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentstatushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Yuk holati tarixi', 'verbose_name_plural': 'Yuk holati tarixi'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_type',
            field=models.CharField(choices=[('office_pickup', 'Qabul qiluvchi ofisdan oladi'), ('courier_delivery', 'Kuryer olib boradi')], default='office_pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_responsibility',
            field=models.CharField(choices=[('sender', 'Yuboruvchi to‘laydi'), ('receiver', 'Qabul qiluvchi to‘laydi')], default='sender', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_type',
            field=models.CharField(choices=[('office_dropoff', 'Jo‘natuvchi ofisga olib keladi'), ('courier_pickup', 'Kuryer chaqirtirish')], default='office_dropoff', max_length=20),
        ),
    ]
