# Generated by Django 5.1.7 on 2025-03-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('client_created', 'Mijoz kiritgan, operator tasdiqini kutmoqda'), ('approved', 'Operator tasdiqladi'), ('in_transit', 'Yo‘lda'), ('arrived', 'Yetib keldi'), ('delivered', 'Topshirildi')], default='client_created', max_length=20),
        ),
    ]
