# Generated by Django 5.1.7 on 2025-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_tracking_code_alter_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmenthistory',
            name='log_data',
        ),
        migrations.AddField(
            model_name='shipmenthistory',
            name='log_text',
            field=models.TextField(blank=True, help_text="Yuk tarixi haqida ma'lumot", null=True),
        ),
    ]
