# Generated by Django 5.1.7 on 2025-03-30 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
