# Generated by Django 5.1.7 on 2025-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_assigned_courier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='assigned_courier',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, help_text='Agar yuridik shaxs bo‘lsa, kompaniya nomi', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Foydalanuvchi telefon raqami', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator'), ('courier', 'Kuryer'), ('physical', 'Jismoniy Shaxs'), ('legal', 'Yuridik Shaxs')], default='physical', help_text='Foydalanuvchi roli', max_length=20),
        ),
    ]
